apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-sample
spec:
  replicas: 2
  selector:
    matchLabels:
      app: flask-sample
  template:
    metadata:
      labels:
        app: flask-sample
    spec:
      containers:
      - name: flask-sample
        image: flask-sample:0.1.0
        ports:
        - containerPort: 8000
        readinessProbe:
          httpGet:
            path: /
            port: 8000
          initialDelaySeconds: 2
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: flask-sample
spec:
  type: NodePort
  selector:
    app: flask-sample
  ports:
  - port: 80
    targetPort: 8000
    nodePort: 30080
